server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/rewinder_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
